#!/bin/bash
echo "MOCK_MYSQLDUMP: $*" >> "${MB_TEST_DIR:-/tmp}/mock_calls.log"
case "$1" in
    --version|-V) echo "mock-mysqldump 1.0" ;;
    *) echo "-- Mock MySQL dump"; echo "CREATE TABLE test (id INT);" ;;
esac
exit 0
